name: Build GPU Machine Image

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 👀
        uses: actions/checkout@v3.0.2
        with:
          persist-credentials: false

      - name: Build AWS images 🔨
        uses: operatehappy/packer-github-actions@master
        with:
          command: build
          arguments: "-var aws_access_key=${{ secrets.AWS_ACCESS_KEY }} -var aws_secret_key=${{ secrets.AWS_SECRET_KEY }}"
          target: build/gpu-host.json
