name: Build Machine Images

on:
  push:
    branches:
      - master

jobs:
  build-cpu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 👀
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Build AWS images 🔨
        uses: operatehappy/packer-github-actions@master
        with:
          command: build
          arguments: "-var aws_access_key=${{ secrets.AWS_ACCESS_KEY }} -var aws_secret_key=${{ secrets.AWS_SECRET_KEY }}"
          target: build/cpu-host.json

  build-gpu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 👀
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Build AWS images 🔨
        uses: operatehappy/packer-github-actions@master
        with:
          command: build
          arguments: "-var aws_access_key=${{ secrets.AWS_ACCESS_KEY }} -var aws_secret_key=${{ secrets.AWS_SECRET_KEY }}"
          target: build/gpu-host.json
